Repository frlp-utn-ingsoft/recalc, pull requests merged in 2023-06, with the labels that each got.

#40 Feature/UI
  .github/workflows/playwright.yml
  .gitignore
  package-lock.json
  package.json
  playwright.config.js
  src/api.js
  src/controllers.js
  src/models.js
  src/public/index.css
  src/public/index.html
  src/public/index.js
  src/public/reset.css
  test/models.test.js
  test/ui.test.js
Labels: enhancement

#42 Feature/eslint
  .eslintignore
  .eslintrc.cjs
  .github/workflows/main.yml
  package-lock.json
  package.json
  src/api.js
  src/public/index.js
Labels: enhancement

#41 Versión 1.3.0
  .eslintignore
  .eslintrc.cjs
  .github/workflows/main.yml
  .github/workflows/playwright.yml
  .gitignore
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  playwright.config.js
  src/api.js
  src/controllers.js
  src/models.js
  src/public/index.css
  src/public/index.html
  src/public/index.js
  src/public/reset.css
  test/models.test.js
  test/ui.test.js
Labels: documentation

#43 Agrega cross-env para que funcionen los e2e en win
  package-lock.json
  package.json
Labels: bug

#44 v1.3.1
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
Labels: documentation

#45 Agrega en que path correr el eslint
  package.json
  src/api.js
Labels: bug

#46 v1.3.2
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  src/api.js
Labels: documentation
