Repository frlp-utn-ingsoft/recalc, pull requests merged in 2023-05, with the labels that each got.

#24 Agrega squelize para el manejo de la db
  .gitignore
  README.md
  package-lock.json
  package.json
  src/controllers.js
  src/models.js
  src/seed.js
Labels: documentation, enhancement

#25 Agrega Integración Continua
  .github/workflows/main.yml
Labels: enhancement

#26 Tests de integración
  package-lock.json
  package.json
  src/api.js
  src/models.js
  src/seed.js
  src/server.js
  test/api.test.js
  test/models.test.js
Labels: enhancement

#27 Versión 1.2.0
  .github/workflows/main.yml
  .gitignore
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  src/api.js
  src/controllers.js
  src/models.js
  src/seed.js
  src/server.js
  test/api.test.js
  test/models.test.js
Labels: documentation
